create database customer_retention ;
use customer_retention ;
select * from orders;

-- =========================================
-- QUERY 1 : BUSINESS DATA HEALTH CHECK
-- =========================================

-- Business Question:
-- What is the overall scale and structure of the business dataset?

-- Why This Matters:
-- Every retention and RFM analysis requires a clear understanding
-- of the total customers, orders, revenue, and transaction timeline.

-- SQL Concepts Used:
-- COUNT(), COUNT DISTINCT, MIN(), MAX(), SUM(), AGGREGATION

-- Key Finding:
-- The business generated approximately 17.37 million in revenue
-- across 779K+ transaction records and nearly 37K unique orders.

SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT customer_id) AS total_customer_id,
    COUNT(DISTINCT invoice) AS unique_orders,
    MIN(DATE(invoicedate)) AS earliest_date,
    MAX(DATE(invoicedate)) AS latest_date,
    SUM(revenue) AS total_revenue
FROM orders;


-- Business Observation
-- The dataset contains 779,425 cleaned transactional records generated by 5,878 unique customers across 36,969 unique orders.
-- The difference between total rows and unique orders indicates that customers frequently purchase multiple products withina single transaction, 
-- reflecting realistic retail purchasing behavior.
-- The transactional history spans from December 2009 to December 2011 providing nearly two years of customer activity suitable for
-- retention, cohort, and RFM analysis.
-- During this period, the business generated approximately 17.37 million in total revenue, indicating a large-scale retail operation
-- with substantial customer purchasing activity.


-- =========================================
-- QUERY 2 : GEOGRAPHIC REVENUE CONCENTRATION
-- =========================================

-- Business Question:
-- Which countries contribute the highest revenue
-- and customer activity to the business?

-- Why This Matters:
-- Understanding geographic concentration helps identify
-- market dependency and expansion opportunities.

-- SQL Concepts Used:
-- GROUP BY, COUNT DISTINCT, SUM(), ORDER BY, LIMIT

-- Key Finding:
-- The United Kingdom contributes more than 82% of total revenue,
-- showing extremely high geographic concentration.

SELECT 
    country,
    ROUND(SUM(revenue), 2) AS revenue,
    COUNT(DISTINCT customer_id) AS total_customer_id
FROM orders
GROUP BY country
ORDER BY revenue DESC
LIMIT 10;

-- Business Observation:
-- The analysis shows that the dataset is heavily dominated
-- by the United Kingdom, contributing approximately 82.4%
-- of total revenue (~14.38 million).
-- This indicates strong dependency on a single market,
-- meaning business performance could be heavily affected
-- by declining demand or churn within the UK region.

-- =========================================
-- QUERY 3 : MONTHLY REVENUE & ORDER TREND
-- =========================================

-- Business Question:
-- Is the business showing seasonal purchasing behavior
-- or stable linear growth over time?

-- Why This Matters:
-- Understanding seasonality helps improve inventory planning,
-- campaign timing, and customer engagement strategies.

-- SQL Concepts Used:
-- DATE FUNCTIONS, GROUP BY, COUNT DISTINCT, SUM(), ORDER BY

-- Key Finding:
-- Revenue and order volume spike significantly
-- during September–November,
-- indicating strong seasonal demand patterns.

SELECT 
    YEAR(invoicedate) AS order_year,
    MONTHNAME(invoicedate) AS month_name,
    COUNT(DISTINCT invoice) AS total_orders,
    SUM(revenue) AS revenue
FROM orders
GROUP BY YEAR(invoicedate), MONTH(invoicedate), MONTHNAME(invoicedate)
ORDER BY order_year, MONTH(invoicedate);

-- Business Observation:
-- Monthly revenue and order volume show clear seasonal fluctuations
-- rather than steady growth.
-- Revenue increased from approximately 558K in January 2010
-- to over 1.16M in November 2010.
-- A similar pattern appears in 2011,
-- where revenue again crossed 1M during October–November.
-- These repeated spikes strongly suggest holiday or festive season demand.



-- =========================================
-- QUERY 4 : HIGH-VALUE CUSTOMERS
-- =========================================

-- Business Question:
-- Which customers contribute the highest revenue
-- and show strong purchasing behavior?

-- Why This Matters:
-- Identifying high-value customers helps the business
-- prioritize retention and loyalty strategies.

-- SQL Concepts Used:
-- GROUP BY, COUNT DISTINCT, MAX(), SUM(), ORDER BY, LIMIT

-- Key Finding:
-- Several customers generated exceptionally high revenue
-- while also maintaining strong repeat purchase behavior.

SELECT 
    customer_id,
    SUM(revenue) AS revenue,
    COUNT(DISTINCT invoice) AS total_orders,
    MAX(DATE(invoicedate)) AS recent_order_date
FROM orders
GROUP BY customer_id
ORDER BY revenue DESC
LIMIT 20;

-- Business Observation:
-- Customer 18102 generated highest total revenue approximately 598K in revenue
-- across 145 orders and remained recently active,
-- indicating strong customer value and engagement.
-- Customer 14911 placed the highest number of orders (398),
-- showing exceptionally strong loyalty behavior.
-- These customers represent potential “Champion” customers
-- who contribute significantly to overall business revenue.


-- =========================================
-- QUERY 5 : CUSTOMER ORDER FREQUENCY DISTRIBUTION
-- =========================================

-- Business Question:
-- What does the customer order frequency distribution look like?

-- Why This Matters:
-- Frequency distribution helps evaluate customer loyalty,
-- repeat purchasing behavior, and churn risk.

-- SQL Concepts Used:
-- CTE, CASE WHEN, GROUP BY, COUNT DISTINCT

-- Key Finding:
-- The largest customer segment consists of repeat buyers
-- placing between 2 and 5 orders.

WITH customer_orders AS (
    SELECT 
        customer_id,
        COUNT(DISTINCT invoice) AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT 
    CASE 
        WHEN order_count = 1 THEN 'One-time buyers'
        WHEN order_count BETWEEN 2 AND 5 THEN 'Repeat buyers'
        WHEN order_count BETWEEN 6 AND 10 THEN 'Frequent buyers'
        WHEN order_count > 10 THEN 'Loyal buyers'
        ELSE 'Other'
    END AS order_frequency_bucket,
    COUNT(*) AS customer_count
FROM customer_orders
GROUP BY 
    CASE 
        WHEN order_count = 1 THEN 'One-time buyers'
        WHEN order_count BETWEEN 2 AND 5 THEN 'Repeat buyers'
        WHEN order_count BETWEEN 6 AND 10 THEN 'Frequent buyers'
        WHEN order_count > 10 THEN 'Loyal buyers'
        ELSE 'Other'
    END;

-- Business Observation:
-- The largest customer segment consists of 2,454 repeat buyers
-- who placed between 2 and 5 orders.
-- The business also has 925 frequent buyers
-- and 876 loyal buyers who placed more than 10 orders.
-- However, 1,623 customers purchased only once,
-- indicating potential customer retention challenges
-- and opportunities to improve repeat purchasing behavior.


-- =========================================
-- QUERY 6 : CUSTOMER LIFECYCLE LENGTH
-- =========================================

-- Business Question:
-- How long do repeat customers typically remain active?

-- Why This Matters:
-- Understanding customer lifecycle length provides context
-- for interpreting recency and retention behavior.

-- SQL Concepts Used:
-- CTE, DATEDIFF, MIN(), MAX(), AVG(), COUNT DISTINCT

-- Key Finding:
-- Repeat customers remain active for approximately 378 days on average.

WITH customer_lifecycle AS (
    SELECT 
        customer_id,
        MIN(DATE(invoicedate)) AS first_purchase,
        MAX(DATE(invoicedate)) AS last_purchase,
        COUNT(DISTINCT invoice) AS total_orders
    FROM orders
    GROUP BY customer_id
)

SELECT 
    AVG(DATEDIFF(last_purchase, first_purchase)) AS avg_days,
    MIN(DATEDIFF(last_purchase, first_purchase)) AS min_days,
    MAX(DATEDIFF(last_purchase, first_purchase)) AS max_days
FROM customer_lifecycle
WHERE total_orders > 1;

-- Business Observation:
-- Customers who purchased more than once remained active
-- for approximately 378 days on average.
-- Some customers placed repeat orders on the same day,
-- while others remained engaged for nearly two years.
-- This wide lifecycle range highlights major differences
-- in customer loyalty and retention behavior.


-- =========================================
-- QUERY 7 : TOP COUNTRY REVENUE CONTRIBUTION
-- =========================================

-- Business Question:
-- Which countries contribute the highest revenue,
-- and how concentrated is the business geographically?

-- Why This Matters:
-- Geographic dependency creates revenue concentration risk
-- and influences expansion strategy decisions.

-- SQL Concepts Used:
-- CTE, WINDOW FUNCTION, GROUP BY, SUM(), COUNT DISTINCT

-- Key Finding:
-- The United Kingdom contributes more than 82%
-- of total business revenue.

WITH country_stats AS (
    SELECT 
        country,
        COUNT(DISTINCT customer_id) AS total_customers,
        SUM(revenue) AS total_revenue
    FROM orders
    GROUP BY country
)
SELECT
    country,
    total_customers,
    total_revenue,
    ROUND(total_revenue / total_customers, 2) AS avg_revenue_per_customer,
    ROUND(total_revenue / SUM(total_revenue) OVER() * 100, 2) AS revenue_pct
FROM country_stats
ORDER BY total_revenue DESC
LIMIT 5;

-- Business Observation:
-- The United Kingdom contributes approximately 82.82%
-- of total business revenue with over 14.38 million in sales.
-- This creates strong geographic concentration risk.
-- Countries such as EIRE and the Netherlands
-- generate extremely high average revenue per customer,
-- indicating the presence of highly valuable international customers.

-- =========================================
-- QUERY 8 : AT-RISK HIGH-VALUE CUSTOMERS
-- =========================================

-- Business Question:
-- Which previously valuable customers
-- have become inactive in the last 90 days?

-- Why This Matters:
-- Identifying high-value inactive customers
-- helps prevent revenue loss through retention strategies.

-- SQL Concepts Used:
-- CTE, DATEDIFF, CROSS JOIN, MAX(), GROUP BY, ORDER BY, LIMIT

-- Key Finding:
-- Several high-revenue customers have become inactive,
-- indicating potential churn risk and future revenue exposure.

WITH customer_summary AS (
    SELECT 
        customer_id,
        MAX(DATE(invoicedate)) AS last_order_date,
        SUM(revenue) AS total_revenue,
        COUNT(DISTINCT invoice) AS total_orders
    FROM orders
    GROUP BY customer_id
),

max_date AS (
    SELECT MAX(DATE(invoicedate)) AS dataset_max_date
    FROM orders
)

SELECT 
    cs.customer_id,
    cs.last_order_date,
    cs.total_revenue,
    cs.total_orders
FROM customer_summary cs
CROSS JOIN max_date md
WHERE DATEDIFF(md.dataset_max_date, cs.last_order_date) > 90
ORDER BY cs.total_revenue DESC
LIMIT 50;

-- Business Observation:
-- Several previously high-value customers
-- have not placed any orders within the last 90 days,
-- indicating strong churn risk.
-- Customer 12346 generated approximately 77.5K in revenue
-- before becoming inactive.
-- Customer 17850 placed 155 orders
-- but has not purchased since December 2010,
-- representing a significant loss of repeat purchasing activity.
-- These customers should be prioritized
-- for re-engagement and retention campaigns.



-- Business question: How much revenue depends on repeat buyers vs one-time buyers?
-- SQL concepts: CTE, CASE WHEN, SUM, window function percentage

WITH customer_type AS (
    SELECT
        customer_id,
        SUM(revenue)              AS customer_revenue,
        COUNT(DISTINCT invoice)   AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT
    CASE
        WHEN order_count = 1 THEN 'One-time buyers'
        ELSE 'Repeat buyers'
    END                                          AS buyer_type,
    COUNT(*)                                     AS customer_count,
    ROUND(SUM(customer_revenue), 2)              AS total_revenue,
    ROUND(SUM(customer_revenue) * 100.0 /
          SUM(SUM(customer_revenue)) OVER (), 1) AS revenue_share_pct
FROM customer_type
GROUP BY 1
ORDER BY total_revenue DESC;

-- Business Observation:

-- The business is heavily dependent on repeat customers,
-- who contribute approximately 16.81 million in revenue,
-- representing 96.8% of total revenue.

-- Although one-time buyers account for 1,623 customers
-- (around 28% of the customer base), they generate only
-- 560K in revenue, contributing just 3.2% of total sales.

-- In contrast, 4,255 repeat buyers generate nearly all
-- business revenue, highlighting the critical importance
-- of customer retention and repeat purchasing behavior.

-- These findings suggest that long-term customer value
-- is created primarily through repeat purchases rather than
-- one-time transactions.

-- The business should continue investing in retention,
-- loyalty programs, and customer engagement initiatives
-- to protect its most valuable customer segment.

-- Any decline in repeat customer activity could have a
-- significant impact on overall revenue performance.



-- Finding: [fill after running]
-- If repeat buyers generate 85%+ of revenue despite being fewer in number,
-- your retention argument is proven with data.............................................................







-- Business question: Do 10% of customers generate the majority of revenue?
-- SQL concepts: CTE, NTILE window function, GROUP BY, percentage

-- Key Finding:
-- The top 10% of customers generate 63.9% of total revenue,
-- while the top 20% generate 77.2%, indicating strong revenue
-- concentration among a small group of high-value customers.

WITH customer_revenue AS (
    SELECT
        customer_id,
        SUM(revenue) AS total_revenue
    FROM orders
    GROUP BY customer_id
),
deciles AS (
    SELECT
        customer_id,
        total_revenue,
        NTILE(10) OVER (ORDER BY total_revenue DESC) AS revenue_decile
    FROM customer_revenue
)
SELECT
    revenue_decile,
    COUNT(*)                                          AS customers,
    ROUND(SUM(total_revenue), 2)                      AS segment_revenue,
    ROUND(SUM(total_revenue) * 100.0 /
          SUM(SUM(total_revenue)) OVER (), 1)         AS revenue_pct,
    ROUND(SUM(SUM(total_revenue)) OVER
          (ORDER BY revenue_decile
           ROWS BETWEEN UNBOUNDED PRECEDING
           AND CURRENT ROW) * 100.0 /
          SUM(SUM(total_revenue)) OVER (), 1)         AS cumulative_pct
FROM deciles
GROUP BY revenue_decile
ORDER BY revenue_decile;

-- Business Observation:

-- Revenue is highly concentrated among a small percentage
-- of customers. The top 10% of customers (Revenue Decile 1)
-- generated approximately 11.11 million in revenue,
-- contributing 63.9% of total business revenue.

-- When the top 20% of customers are combined,
-- they account for 77.2% of total revenue,
-- which is very close to the classic Pareto Principle
-- where a small percentage of customers drive the majority
-- of business performance.

-- The top 30% of customers contribute 85% of total revenue,
-- indicating that revenue generation is heavily dependent
-- on a relatively small group of high-value customers.

-- This creates customer concentration risk, as losing even
-- a small number of these high-value customers could have
-- a significant impact on overall revenue.

-- The business should prioritize retention, loyalty programs,
-- and personalized engagement strategies for top-spending
-- customers to protect a substantial portion of revenue.

-- At the same time, opportunities exist to increase the value
-- of lower-spending customer segments and reduce dependency
-- on the highest-value customers.